Harden Java launcher and support container options

diff --git a/bin/msoyjava b/bin/msoyjava
--- a/bin/msoyjava
+++ b/bin/msoyjava
@@ -1,70 +1,77 @@
 #!/bin/sh
 #
-# $Id$
-#
-# Sets up standard bits and runs java
+# Sets up standard bits and runs java.
 
-# Check operating system type
-case "`uname`" in
-  CYGWIN*) CYGWIN=yes;;
+set -e
+
+CYGWIN=
+case "$(uname)" in
+  CYGWIN*) CYGWIN=yes ;;
 esac
 
-MSOY_HOME=`dirname $0`
-MSOY_HOME=`cd $MSOY_HOME/.. ; pwd`
-[ -z "$CYGWIN" ] || MSOY_HOME="`cygpath -wam "$MSOY_HOME"`"
+MSOY_HOME=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
+[ -z "$CYGWIN" ] || MSOY_HOME=$(cygpath -wam "$MSOY_HOME")
 
 umask 002
 
-JAVA_VM="`which java`"
-if [ ! -e "$JAVA_VM" ]; then
-    echo "$0: Cannot find JVM. Exiting."
+JAVA_VM=$(command -v java || true)
+if [ -z "$JAVA_VM" ] || [ ! -x "$JAVA_VM" ]; then
+    echo "$0: Cannot find JVM. Exiting." >&2
     exit 255
 fi
 
-if [ -z "$1" ]; then
-    echo "Usage: $0 conf_prefix [arg ...]"
+if [ "$#" -eq 0 ]; then
+    echo "Usage: $0 conf_prefix [arg ...]" >&2
     exit 255
 fi
 
-CONF_PREFIX="$1"
+CONF_PREFIX=$1
 shift
+CONF_FILE="$MSOY_HOME/dist/${CONF_PREFIX}-server.conf"
 
-# Obtain settings from MSOY_HOME/dist/${CONF_PREFIX}-server.conf
-if [ -f $MSOY_HOME/dist/${CONF_PREFIX}-server.conf ]; then
-    . $MSOY_HOME/dist/${CONF_PREFIX}-server.conf
+# Obtain settings from MSOY_HOME/dist/${CONF_PREFIX}-server.conf.
+if [ -r "$CONF_FILE" ]; then
+    . "$CONF_FILE"
 else
-    echo "Unable to read ${CONF_PREFIX}-server.conf."
-    echo "Usage: $0 conf_prefix [arg ...]"
+    echo "Unable to read $CONF_FILE." >&2
+    echo "Usage: $0 conf_prefix [arg ...]" >&2
     exit 255
 fi
 
-# set up our java arguments
+RSRC_CACHE_DIR=${MSOY_RSRC_CACHE_DIR:-/tmp/msoy}
+mkdir -p "$RSRC_CACHE_DIR"
+
 JAVA_ARGS="-Dno_unpack_resources=true \
     -Dresource_dir=$MSOY_HOME/rsrc \
-    -Drsrc_cache_dir=/tmp \
+    -Drsrc_cache_dir=$RSRC_CACHE_DIR \
     -Djava.util.logging.config.file=$MSOY_HOME/etc/logging.properties"
 
-# set up a custom SMTP host
-if [ ! -z "$SMTP_HOST" ]; then
+if [ -n "${SMTP_HOST:-}" ]; then
     JAVA_ARGS="$JAVA_ARGS -Dmail.smtp.host=$SMTP_HOST"
 fi
 
-# extract -D arguments so that we can put them before the classname
-while [ ! -z "$1" ]; do
+if [ -n "${SERVER_MEMORY:-}" ]; then
+    JAVA_ARGS="$JAVA_ARGS -Xmx$SERVER_MEMORY"
+fi
+
+if [ -n "${MSOY_JAVA_OPTS:-}" ]; then
+    JAVA_ARGS="$JAVA_ARGS $MSOY_JAVA_OPTS"
+fi
+
+ARGS=
+# Extract -D arguments so they are guaranteed to appear before the classname.
+while [ "$#" -gt 0 ]; do
     case "$1" in
         -D*)
             JAVA_ARGS="$JAVA_ARGS $1"
             ;;
-
         -debugger)
-            JDWP_ARGS="transport=dt_socket,server=y,address=8000,suspend=n";
+            JDWP_ARGS="transport=dt_socket,server=y,address=8000,suspend=n"
             JAVA_ARGS="-agentlib:jdwp=$JDWP_ARGS $JAVA_ARGS"
             ;;
-
         -jconsole)
             JAVA_ARGS="-Dcom.sun.management.jmxremote $JAVA_ARGS"
             ;;
-
         *)
             ARGS="$ARGS $1"
             ;;
@@ -74,14 +81,15 @@ done
 
 { [ -z "$CYGWIN" ] && SEP=:; } || SEP=';'
 
-# Add all necessary JAR files to the CLASSPATH
 CLASSPATH=$MSOY_HOME/dist
-for JAR in $MSOY_HOME/dist/lib/*.jar $MSOY_HOME/dist/msoy-*.jar; do
-    if [ -e $JAR ]; then
+for JAR in "$MSOY_HOME"/dist/lib/*.jar "$MSOY_HOME"/dist/msoy-*.jar; do
+    if [ -e "$JAR" ]; then
         CLASSPATH="$CLASSPATH$SEP$JAR"
     fi
 done
 export CLASSPATH
 
-# do the deed
+# JAVA_ARGS and ARGS intentionally undergo shell word splitting because they are
+# assembled from individual JVM arguments above and by the legacy launchers.
+# shellcheck disable=SC2086
 exec "$JAVA_VM" $JAVA_ARGS $ARGS
